tools/importer/import.js
See #1 
URL for testing:
- https://import-part1--stewart--hlxsites.hlx.page/
This includes the first pass on import code, additional improvements will be logged in follow-up issues.  The general set of content was imported here: https://adobe.sharepoint.com/sites/HelixProjects/Shared%20Documents/Forms/AllItems.aspx?FolderCTID=0x012000FF16C1F85E2B3849A4CD207A7190B18C&id=%2Fsites%2FHelixProjects%2FShared%20Documents%2Fsites%2Fstewart%2Dtitle%2Fdrafts%2Fbrobert&viewid=124ad5f1%2D60ba%2D476c%2Dade8%2D7c1df274ee95
=> Import for general content - take 1

tools/importer/import.js
Fix #1 
Issues with columns, embeds, lists and styles addressed.  Also added basic support for app and marketto forms if they're found so we can at least track where they appear.
URL for testing:
- https://import-part2--stewart--hlxsites.hlx.page/
=> Import part2

tools/importer/import.js
Fix #1
Fixes issues identified in part 2
Test URLs:
- Before: https://main--stewart--hlxsites.hlx.page/
- After: https://import-part3--stewart--hlxsites.hlx.page/drafts/import/en
=> Import part3

blocks/hero/hero.css, blocks/hero/hero.js, scripts/scripts.js
Fix #4 
Updated the auto-block logic on Hero to exclude Section metadata and updated styles to match the site.
Test URLs:
- Before: https://main--stewart--hlxsites.hlx.page/en
- After: https://hero-auto-block--stewart--hlxsites.hlx.page/en
- Before: https://main--stewart--hlxsites.hlx.page/drafts/import/en/about-stewart/careers
- After: https://hero-auto-block--stewart--hlxsites.hlx.page/drafts/import/en/about-stewart/careers
=> Hero auto block

tools/importer/import.js
Fix #24 
Small improvements for handling tables in press releases and some other optimizations/fixes
Test URLs:
- Before: https://main--stewart--hlxsites.hlx.page/
- After: https://news-import--stewart--hlxsites.hlx.page/
=> News import

blocks/accordion/accordion.css, blocks/accordion/accordion.js, styles/styles.css, tools/importer/import.js
Fix #12 
If you introduces a new block/varaint, please update the block library https://main--stewart--hlxsites.hlx.page/tools/sidekick/library/library.html
Test URLs:
- [Before](https://main--stewart--hlxsites.hlx.page/tools/sidekick/library/library.html)
- [After](https://feat-accordion-block--stewart--hlxsites.hlx.page/tools/sidekick/library/library.html)
- Live Site: https://www.stewart.com/en/what-we-offer/underwriting.html
- [Before](https://main--stewart--hlxsites.hlx.page/drafts/import/en/what-we-offer/underwriting)
- [After](https://feat-accordion-block--stewart--hlxsites.hlx.page/drafts/import/en/what-we-offer/underwriting)
- Tested …
=> feat: implement accordion block

blocks/columns/columns.css, blocks/columns/columns.js, tools/importer/import.js
Fix #17 
Updated the columns block to support 66-33, 75-25, 33-33-33 variations and grey, teal backgrounds
Variations can be found below
https://columns-block--stewart--hlxsites.hlx.page/tools/sidekick/library/library.html
Test URLs:
- After: https://columns-block--stewart--hlxsites.hlx.page/en
=> Column block updated to support different variations

.github/pull_request_template.md, blocks/carousel/carousel.css, blocks/carousel/carousel.js
Fix #16 
If you introduces a new block/varaint, please update the block library https://main--stewart--hlxsites.hlx.page/tools/sidekick/library/library.html
Test URLs:
- Before: https://main--stewart--hlxsites.hlx.page/drafts/import/en/about-stewart/sustainability
- After: https://image-carousel--stewart--hlxsites.hlx.page/drafts/import/en/about-stewart/sustainability
- Library: https://image-carousel--stewart--hlxsites.hlx.page/library/blocks/carousel
=> Image carousel

blocks/footer/footer.css
Fix #3 
**Test URLs:**
- After: https://bugfix-footer-social-icons--stewart--hlxsites.hlx.live/
**Screenshots:**
Before
After
=> fix: update styling for footer social icons

blocks/carousel/carousel.css, blocks/columns/columns.js
Fix #18 
Test URLs:
- Before: https://main--stewart--hlxsites.hlx.page/drafts/import/en/about-stewart/careers
- After: https://columns-carousel--stewart--hlxsites.hlx.page/drafts/import/en/about-stewart/careers
=> Fix Column block - Carousel variant #18

tools/importer/import.js
See #27 
Test URLs:
- After: https://import-next--stewart--hlxsites.hlx.live/
=> Import next

blocks/embed/embed.css, blocks/embed/embed.js, scripts/scripts.js
Fix #62 
Adds embed block and auto-blocking for youtube embed links
Test URLs:
- Before: https://main--stewart--hlxsites.hlx.page/drafts/import/en/landing-pages/2022-ace
- After: https://embed-youtube--stewart--hlxsites.hlx.page/drafts/import/en/landing-pages/2022-ace
=> Add embed block and auto-block for youtube embed links

blocks/hero/hero.css
Fix #65 
Updated the block library https://main--stewart--hlxsites.hlx.page/tools/sidekick/library/library.html
Test URLs:
- Before: https://main--stewart--hlxsites.hlx.page/drafts/import/en
- After: https://hero-narrow--stewart--hlxsites.hlx.page/drafts/import/en
=> Hero narrow variation updated

styles/styles.css
Fix #64 
Test URLs:
- Before: https://main--stewart--hlxsites.hlx.page/drafts/import/en/about-stewart/careers
- After: https://dark-links--stewart--hlxsites.hlx.page/drafts/import/en/about-stewart/careers
=> Fix links in black backgrounds should be teal #64

blocks/header/header.css, blocks/header/header.js, blocks/search-results/search-results.css, blocks/search-results/search-results.js, scripts/ffetch.js, scripts/scripts.js, scripts/search-utils.js, styles/styles.css
**SUMMARY**
- Fix #7 
- Number of results per page is configurable at the block level for search results, defaults to 20 if none provided.
**Test URLs:**
- Before: https://main--stewart--hlxsites.hlx.live/search-results?q=stewart
- After: https://feature-search--stewart--hlxsites.hlx.live/search-results?q=stewart
=> feat: implement site search

blocks/columns/columns.css
Fix #63 
Updated https://main--stewart--hlxsites.hlx.page/tools/sidekick/library/library.html
Test URLs:
- Before: https://main--stewart--hlxsites.hlx.page/en
- After: https://column-variation--stewart--hlxsites.hlx.page/en
=> left border variation added on columns

blocks/header/header.js
Fix #78 
Test URLs:
- After: https://header-fix--stewart--hlxsites.hlx.live/
=> fix mobile header expanded section on open

blocks/columns/columns.css, blocks/columns/columns.js, blocks/hero/hero.css, blocks/list/list.css, blocks/list/list.js, styles/styles.css, tools/importer/import.js
Fix #70 
Test URLs:
- Before: https://main--stewart--hlxsites.hlx.live/en
- After: https://card-style--stewart--hlxsites.hlx.page/en
=> card style for columns and list blocks udpated

blocks/blockquote/blockquote.css, blocks/blockquote/blockquote.js, scripts/scripts.js, styles/styles.css, tools/importer/import.js
Fix #68 
Test URLs:
- Before: https://main--stewart--hlxsites.hlx.page/library/blocks/blockquote
- After: https://feature-blockquote--stewart--hlxsites.hlx.page/library/blocks/blockquote
=> feat: implement blockquote

scripts/scripts.js, styles/lazy-styles.css, styles/styles.css, tools/importer/import.js
Test URLs:
- After: https://importer-changes--stewart--hlxsites.hlx.live/
=> Importer changes

blocks/search-results/search-results.js, scripts/search-utils.js, styles/styles.css
Fix #89 
Test URLs:
- After: https://redict-search--stewart--hlxsites.hlx.live/en/real-estate-dictionary
=> added re dict search

styles/styles.css
Fix #57 
updated https://button-styles--stewart--hlxsites.hlx.page/tools/sidekick/library/library.html?plugin=blocks&path=/library/blocks/buttons&index=0 with button examples
Test URLs:
- After: https://button-styles--stewart--hlxsites.hlx.live/
=> secondary and tertiary button styles

blocks/columns/columns.css, styles/styles.css
Fix #96 
Test URLs:
- Before: https://main--stewart--hlxsites.hlx.page/en/what-we-offer/insurance
- After: https://feature-section-left-border--stewart--hlxsites.hlx.page/en/what-we-offer/insurance
Block library updated: https://feature-section-left-border--stewart--hlxsites.hlx.page/library/blocks/section-backgrounds
=> feat: add left border option for sections

blocks/columns/columns.css, blocks/search-results/search-results.js, scripts/search-utils.js, scripts/taxonomy.js, tools/importer/import.js, tools/sidekick/config.json, tools/sidekick/tagger/tagger.css, tools/sidekick/tagger/tagger.html, tools/sidekick/tagger/tagger.js
Fix #93 
Test URLs:
- After: https://taxonomy-tagger--stewart--hlxsites.hlx.live/tools/sidekick/tagger/tagger.html
- After: https://taxonomy-tagger--stewart--hlxsites.hlx.live/en/insights/insights-all
=> Taxonomy tagger

scripts/scripts.js, templates/blog-article-page/blog-article-page.css, templates/blog-article-page/blog-article-page.js, tools/importer/import.js
Fix #82 
Test URLs:
- After: https://blog-styling--stewart--hlxsites.hlx.live/en/insights/2023/6-things-to-keep-pristine-for-spring
Note importer changes to remove author and date, will fix duplication on re-import.
=> Blog styling

blocks/calculator/amortization.js, blocks/calculator/calculator.js, blocks/calculator/deedstamps.js, blocks/calculator/markup.js, blocks/calculator/mortgage.js
Fix #122 
Test URLs:
- Before: https://main--stewart--hlxsites.hlx.live/en/news
- After: https://calculator--stewart--hlxsites.hlx.live/en/news
=> mortgage calculator implemented

blocks/columns/columns.css, blocks/columns/columns.js
Fix #108 
If your PR introduces a new block/black variant, please update the block library https://main--stewart--hlxsites.hlx.page/tools/sidekick/library/library.html
Test URLs:
- Before: https://main--stewart--hlxsites.hlx.live/en
- After: https://columns-tablet--stewart--hlxsites.hlx.live/en
=> add row class to all rows in columns, reduce padding in tablet

blocks/form/form.css, blocks/form/form.js, scripts/scripts.js, styles/styles.css
See #90 
Introduces form generation, still have some work to do but would like to merge as it's at a good point to help get page layouts working, etc.
Test URLs:
- Before: https://main--stewart--hlxsites.hlx.live/en/about-stewart/supplier-diversity-at-stewart
- After: https://form-gen--stewart--hlxsites.hlx.live/en/about-stewart/supplier-diversity-at-stewart
=> fast-forward merge on current main branch

blocks/footer/footer.css, blocks/footer/footer.js, scripts/scripts.js, styles/styles.css, templates/landing-page/landing-page.css, templates/landing-page/landing-page.js, tools/importer/import.js
See #20 
Test URLs:
- After: https://landing-pages--stewart--hlxsites.hlx.live/
- After: https://landing-pages--stewart--hlxsites.hlx.page/en/landing-pages/commercial-escrow/litigation-guarantee
=> footers for landing pages

blocks/calculator/amortization.js, blocks/calculator/calculator.css, blocks/calculator/markup.js
Fix #130 
Test URLs:
- Before: https://main--stewart--hlxsites.hlx.live/en/real-estate-dictionary/amortization
- After: https://calculator--stewart--hlxsites.hlx.live/en/real-estate-dictionary/amortization
=> calculator hard coded strings replaced with placeholders

blocks/form/form.js, blocks/fragment/fragment.js, scripts/scripts.js, templates/blog-article-page/blog-article-page.js
Fix #121
Test URLs:
https://form-autoblock--stewart--hlxsites.hlx.live/en/about-stewart/supplier-diversity-at-stewart
=> Form autoblock

blocks/search-results/search-results.js
Fix #116 
Test URLs:
- Before: https://main--stewart--hlxsites.hlx.live/en/search-result?q=stewart
- After: https://bugfix-search-placeholders--stewart--hlxsites.hlx.live/en/search-result?q=stewart
=> fix: remove hard coded strings from search results, udpate with placeholders

blocks/card/card.css, blocks/card/card.js, blocks/columns/columns.css, blocks/columns/columns.js, blocks/hero/hero.css, blocks/list/list.js, scripts/scripts.js, styles/styles.css, templates/landing-page/landing-page.js, tools/importer/import.js
See #20 
https://landing-pages-next--stewart--hlxsites.hlx.live/en/landing-pages/2022-ace
https://landing-pages-next--stewart--hlxsites.hlx.live/en/landing-pages/certifid
https://landing-pages-next--stewart--hlxsites.hlx.live/en/landing-pages/chron-100
also impacts card columns, some places I checked, but may worth checking others
https://landing-pages-next--stewart--hlxsites.hlx.live/en/legal-contacts
https://landing-pages-next--stewart--hlxsites.hlx.live/en/customer-type/commercial-title-closing-services/title-and-closing-services/ucc-one
=> Landing pages next

blocks/form/form.js, scripts/scripts.js, tools/sidekick/config.json, tools/sidekick/form-helper/form-helper.css, tools/sidekick/form-helper/form-helper.html, tools/sidekick/form-helper/form-helper.js
Fix #136 
This moves the easter-egg form helper into a more official and usable sidekick plugin.
Test URLs:
- Before: https://main--stewart--hlxsites.hlx.live/en/about-stewart/supplier-diversity-at-stewart
- After: https://form-helper-take2--stewart--hlxsites.hlx.live/en/about-stewart/supplier-diversity-at-stewart
=> Form helper take2

blocks/header/header.js, blocks/search-results/search-results.js, scripts/scripts.js, scripts/search-utils.js
See #156 
Test URLs:
- After: https://duplicated-nav-load--stewart--hlxsites.hlx.live/
=> refactor search form loading to remove redundant fetches of header html

blocks/form/form.css, blocks/form/form.js, styles/styles.css
Fix #92 
Test URLs:
- Before: https://main--stewart--hlxsites.hlx.page/en/new-hire/new-hire-program-available-items
- After: https://js-forms--stewart--hlxsites.hlx.page/en/new-hire/new-hire-program-available-items
=> new hire gift form implemented
